---
slug: softcover_youtube_api
filename: softcover_youtube_api
title: Hacking the YouTube API
subtitle: Build a Single Page App on YouTube
description: Change me.
author: Mark Maximus Muskardin
copyright: 2014
uuid: 53a593bf-fdba-4fee-867c-8c3619b2762d
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
